name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checkout the code from our repo

      - uses: actions/setup-node@v4 # Set up the Node.js environment
        with:
          node-version: 22
          cache: npm

      
      - run: npm ci # still needed after cache as it rebuilds node_modules
      - run: npm run lint
      # - name: Super-linter
      #   uses: super-linter/super-linter@v8.7.0 # x-release-please-version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         env:


# name: Lint
#
# on: # yamllint disable-line rule:truthy
#   push: null
#   pull_request: null

# permissions: {}

# jobs:
#   build:
#     name: Lint
#     runs-on: ubuntu-latest

#     permissions:
#       # contents permission to clone the repository
#       contents: read
#       packages: read
#       # issues and pull-requests permissions to write results as pull
#       # request comments. Omit them if you don't need summary comments
#       issues: write
#       pull-requests: write
#       # To report GitHub Actions status checks. Omit if you don't need
#       # to update commit status
#       statuses: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v6
#         with:
#           # super-linter needs the full git history to get the
#           # list of files that changed across commits
#           fetch-depth: 0
#           persist-credentials: false

#       - name: Super-linter
#         uses: super-linter/super-linter@v8.7.0 # x-release-please-version
#         env:
#           # To report GitHub Actions status checks
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # lint:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     issues: write
  #     pull-requests: write
  #     statuses: write

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Run Super-Linter
  #       uses: super-linter/super-linter@v8.7.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
