name: CI

# 1. State the behavior that triggers this workflow
on:
  push:
    branches:
      - main
  pull_request:

# Handle behavior of mult workflows, cancel old workflow on push of new one
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


# Matrices -> mult runners to see how this should behave

# 2. Job
jobs:

  test:
    runs-on: ubuntu-latest

    # Permissions
    permissions: 
      contents: read
      pull-requests: write
      statuses: write


    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # Checkout the code from our repo
        with:
          fetch-depth: 0 # Add git history of past 2 pushed repos (for now)
          persist-credentials: false


      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # Set up the Node.js environment
        with:
          node-version: 22
          cache: npm

      
      - run: npm ci # still needed after cache as it rebuilds node_modules
      - run: npm run lint
      - run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY}}
          NEXT_PUBLIC_SUPABASE_URL: ${{secrets.NEXT_PUBLIC_SUPABASE_URL}}
      # - name: Super-linter
      #   uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # x-release-please-version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm test
#         env:
  

# name: Lint
#
# on: # yamllint disable-line rule:truthy
#   push: null
#   pull_request: null

# permissions: {}

# jobs:
#   build:
#     name: Lint
#     runs-on: ubuntu-latest

#     permissions:
#       # contents permission to clone the repository
#       contents: read
#       packages: read
#       # issues and pull-requests permissions to write results as pull
#       # request comments. Omit them if you don't need summary comments
#       issues: write
#       pull-requests: write
#       # To report GitHub Actions status checks. Omit if you don't need
#       # to update commit status
#       statuses: write

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v6
#         with:
#           # super-linter needs the full git history to get the
#           # list of files that changed across commits
#           fetch-depth: 0
#           persist-credentials: false

#       - name: Super-linter
#         uses: super-linter/super-linter@v8.7.0 # x-release-please-version
#         env:
#           # To report GitHub Actions status checks
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # lint:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     issues: write
  #     pull-requests: write
  #     statuses: write

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Run Super-Linter
  #       uses: super-linter/super-linter@v8.7.0
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  #   permissions:
  #     contents: read
  #     issues: write
  #     pull-requests: write
  #     statuses: write